<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ViolationSanctionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('violation_sanctions')->insert([
            ['id' => 1, 'violation_id' => 1, 'no_of_offense' => 1, 'sanction_id' => 1],
            ['id' => 2, 'violation_id' => 1, 'no_of_offense' => 2, 'sanction_id' => 2],
            ['id' => 3, 'violation_id' => 1, 'no_of_offense' => 3, 'sanction_id' => 3],
            ['id' => 4, 'violation_id' => 1, 'no_of_offense' => 4, 'sanction_id' => 4],
            ['id' => 5, 'violation_id' => 2, 'no_of_offense' => 1, 'sanction_id' => 1],
            ['id' => 6, 'violation_id' => 2, 'no_of_offense' => 2, 'sanction_id' => 2],
            ['id' => 7, 'violation_id' => 2, 'no_of_offense' => 3, 'sanction_id' => 3],
            ['id' => 8, 'violation_id' => 2, 'no_of_offense' => 4, 'sanction_id' => 4],
            ['id' => 9, 'violation_id' => 3, 'no_of_offense' => 1, 'sanction_id' => 5],
            ['id' => 10, 'violation_id' => 3, 'no_of_offense' => 2, 'sanction_id' => 6],
            ['id' => 11, 'violation_id' => 3, 'no_of_offense' => 3, 'sanction_id' => 7],
            ['id' => 12, 'violation_id' => 4, 'no_of_offense' => 1, 'sanction_id' => 4],
            ['id' => 13, 'violation_id' => 4, 'no_of_offense' => 2, 'sanction_id' => 8],
            ['id' => 14, 'violation_id' => 4, 'no_of_offense' => 3, 'sanction_id' => 9],
            ['id' => 15, 'violation_id' => 5, 'no_of_offense' => 1, 'sanction_id' => 1],
            ['id' => 16, 'violation_id' => 5, 'no_of_offense' => 2, 'sanction_id' => 2],
            ['id' => 17, 'violation_id' => 5, 'no_of_offense' => 3, 'sanction_id' => 3],
            ['id' => 18, 'violation_id' => 5, 'no_of_offense' => 4, 'sanction_id' => 4],
            ['id' => 19, 'violation_id' => 6, 'no_of_offense' => 1, 'sanction_id' => 10],
            ['id' => 20, 'violation_id' => 6, 'no_of_offense' => 2, 'sanction_id' => 11],
            ['id' => 21, 'violation_id' => 6, 'no_of_offense' => 3, 'sanction_id' => 12],
            ['id' => 22, 'violation_id' => 6, 'no_of_offense' => 4, 'sanction_id' => 4],
            ['id' => 23, 'violation_id' => 7, 'no_of_offense' => 1, 'sanction_id' => 2],
            ['id' => 24, 'violation_id' => 7, 'no_of_offense' => 2, 'sanction_id' => 4],
            ['id' => 25, 'violation_id' => 7, 'no_of_offense' => 3, 'sanction_id' => 8],
            ['id' => 26, 'violation_id' => 7, 'no_of_offense' => 4, 'sanction_id' => 9],
            ['id' => 27, 'violation_id' => 8, 'no_of_offense' => 1, 'sanction_id' => 10],
            ['id' => 28, 'violation_id' => 8, 'no_of_offense' => 2, 'sanction_id' => 11],
            ['id' => 29, 'violation_id' => 8, 'no_of_offense' => 3, 'sanction_id' => 12],
            ['id' => 30, 'violation_id' => 8, 'no_of_offense' => 4, 'sanction_id' => 4],
            ['id' => 31, 'violation_id' => 9, 'no_of_offense' => 1, 'sanction_id' => 2],
            ['id' => 32, 'violation_id' => 9, 'no_of_offense' => 2, 'sanction_id' => 4],
            ['id' => 33, 'violation_id' => 9, 'no_of_offense' => 3, 'sanction_id' => 8],
            ['id' => 34, 'violation_id' => 9, 'no_of_offense' => 4, 'sanction_id' => 9],
            ['id' => 35, 'violation_id' => 10, 'no_of_offense' => 1, 'sanction_id' => 11],
            ['id' => 36, 'violation_id' => 10, 'no_of_offense' => 2, 'sanction_id' => 2],
            ['id' => 37, 'violation_id' => 10, 'no_of_offense' => 3, 'sanction_id' => 4],
            ['id' => 38, 'violation_id' => 10, 'no_of_offense' => 4, 'sanction_id' => 8],
            ['id' => 39, 'violation_id' => 11, 'no_of_offense' => 1, 'sanction_id' => 3],
            ['id' => 40, 'violation_id' => 11, 'no_of_offense' => 2, 'sanction_id' => 4],
            ['id' => 41, 'violation_id' => 11, 'no_of_offense' => 3, 'sanction_id' => 8],
            ['id' => 42, 'violation_id' => 11, 'no_of_offense' => 4, 'sanction_id' => 9],
            ['id' => 43, 'violation_id' => 12, 'no_of_offense' => 1, 'sanction_id' => 11],
            ['id' => 44, 'violation_id' => 12, 'no_of_offense' => 2, 'sanction_id' => 1],
            ['id' => 45, 'violation_id' => 12, 'no_of_offense' => 3, 'sanction_id' => 4],
            ['id' => 46, 'violation_id' => 12, 'no_of_offense' => 4, 'sanction_id' => 8],
            ['id' => 47, 'violation_id' => 13, 'no_of_offense' => 1, 'sanction_id' => 11],
            ['id' => 48, 'violation_id' => 13, 'no_of_offense' => 2, 'sanction_id' => 2],
            ['id' => 49, 'violation_id' => 13, 'no_of_offense' => 3, 'sanction_id' => 4],
            ['id' => 50, 'violation_id' => 13, 'no_of_offense' => 4, 'sanction_id' => 8],
            ['id' => 51, 'violation_id' => 14, 'no_of_offense' => 1, 'sanction_id' => 11],
            ['id' => 52, 'violation_id' => 14, 'no_of_offense' => 2, 'sanction_id' => 17],
            ['id' => 53, 'violation_id' => 14, 'no_of_offense' => 3, 'sanction_id' => 18],
            ['id' => 54, 'violation_id' => 14, 'no_of_offense' => 4, 'sanction_id' => 19],
            ['id' => 55, 'violation_id' => 15, 'no_of_offense' => 1, 'sanction_id' => 2],
            ['id' => 56, 'violation_id' => 15, 'no_of_offense' => 2, 'sanction_id' => 4],
            ['id' => 57, 'violation_id' => 15, 'no_of_offense' => 3, 'sanction_id' => 8],
            ['id' => 58, 'violation_id' => 15, 'no_of_offense' => 4, 'sanction_id' => 9],
            ['id' => 59, 'violation_id' => 16, 'no_of_offense' => 1, 'sanction_id' => 4],
            ['id' => 60, 'violation_id' => 16, 'no_of_offense' => 2, 'sanction_id' => 8],
            ['id' => 61, 'violation_id' => 16, 'no_of_offense' => 3, 'sanction_id' => 9],
            ['id' => 62, 'violation_id' => 17, 'no_of_offense' => 1, 'sanction_id' => 2],
            ['id' => 63, 'violation_id' => 17, 'no_of_offense' => 2, 'sanction_id' => 4],
            ['id' => 64, 'violation_id' => 17, 'no_of_offense' => 3, 'sanction_id' => 8],
            ['id' => 65, 'violation_id' => 17, 'no_of_offense' => 4, 'sanction_id' => 9],
            ['id' => 66, 'violation_id' => 18, 'no_of_offense' => 1, 'sanction_id' => 2],
            ['id' => 67, 'violation_id' => 18, 'no_of_offense' => 2, 'sanction_id' => 4],
            ['id' => 68, 'violation_id' => 18, 'no_of_offense' => 3, 'sanction_id' => 8],
            ['id' => 69, 'violation_id' => 18, 'no_of_offense' => 4, 'sanction_id' => 9],
            ['id' => 70, 'violation_id' => 19, 'no_of_offense' => 1, 'sanction_id' => 4],
            ['id' => 71, 'violation_id' => 19, 'no_of_offense' => 2, 'sanction_id' => 8],
            ['id' => 72, 'violation_id' => 19, 'no_of_offense' => 3, 'sanction_id' => 9],
            ['id' => 73, 'violation_id' => 20, 'no_of_offense' => 1, 'sanction_id' => 4],
            ['id' => 74, 'violation_id' => 20, 'no_of_offense' => 2, 'sanction_id' => 8],
            ['id' => 75, 'violation_id' => 20, 'no_of_offense' => 3, 'sanction_id' => 9],
            ['id' => 76, 'violation_id' => 21, 'no_of_offense' => 1, 'sanction_id' => 4],
            ['id' => 77, 'violation_id' => 21, 'no_of_offense' => 2, 'sanction_id' => 8],
            ['id' => 78, 'violation_id' => 21, 'no_of_offense' => 3, 'sanction_id' => 9],
            ['id' => 79, 'violation_id' => 22, 'no_of_offense' => 1, 'sanction_id' => 2],
            ['id' => 80, 'violation_id' => 22, 'no_of_offense' => 2, 'sanction_id' => 4],
            ['id' => 81, 'violation_id' => 22, 'no_of_offense' => 3, 'sanction_id' => 8],
            ['id' => 82, 'violation_id' => 22, 'no_of_offense' => 4, 'sanction_id' => 9],
            ['id' => 83, 'violation_id' => 23, 'no_of_offense' => 1, 'sanction_id' => 4],
            ['id' => 84, 'violation_id' => 23, 'no_of_offense' => 2, 'sanction_id' => 8],
            ['id' => 85, 'violation_id' => 23, 'no_of_offense' => 3, 'sanction_id' => 9],
            ['id' => 86, 'violation_id' => 24, 'no_of_offense' => 1, 'sanction_id' => 8],
            ['id' => 87, 'violation_id' => 24, 'no_of_offense' => 2, 'sanction_id' => 9],
            ['id' => 88, 'violation_id' => 25, 'no_of_offense' => 1, 'sanction_id' => 4],
            ['id' => 89, 'violation_id' => 25, 'no_of_offense' => 2, 'sanction_id' => 8],
            ['id' => 90, 'violation_id' => 25, 'no_of_offense' => 3, 'sanction_id' => 9],
            ['id' => 91, 'violation_id' => 26, 'no_of_offense' => 1, 'sanction_id' => 11],
            ['id' => 92, 'violation_id' => 26, 'no_of_offense' => 2, 'sanction_id' => 17],
            ['id' => 93, 'violation_id' => 26, 'no_of_offense' => 3, 'sanction_id' => 18],
            ['id' => 94, 'violation_id' => 26, 'no_of_offense' => 4, 'sanction_id' => 19],
            ['id' => 95, 'violation_id' => 27, 'no_of_offense' => 1, 'sanction_id' => 4],
            ['id' => 96, 'violation_id' => 27, 'no_of_offense' => 2, 'sanction_id' => 8],
            ['id' => 97, 'violation_id' => 27, 'no_of_offense' => 3, 'sanction_id' => 9],
            ['id' => 98, 'violation_id' => 28, 'no_of_offense' => 1, 'sanction_id' => 4],
            ['id' => 99, 'violation_id' => 28, 'no_of_offense' => 2, 'sanction_id' => 8],
            ['id' => 100, 'violation_id' => 28, 'no_of_offense' => 3, 'sanction_id' => 9],
            ['id' => 101, 'violation_id' => 29, 'no_of_offense' => 1, 'sanction_id' => 13],
            ['id' => 102, 'violation_id' => 29, 'no_of_offense' => 2, 'sanction_id' => 14],
            ['id' => 103, 'violation_id' => 29, 'no_of_offense' => 3, 'sanction_id' => 9],
            ['id' => 104, 'violation_id' => 30, 'no_of_offense' => 1, 'sanction_id' => 15],
            ['id' => 105, 'violation_id' => 31, 'no_of_offense' => 1, 'sanction_id' => 4],
            ['id' => 106, 'violation_id' => 31, 'no_of_offense' => 2, 'sanction_id' => 8],
            ['id' => 107, 'violation_id' => 31, 'no_of_offense' => 3, 'sanction_id' => 9],
            ['id' => 108, 'violation_id' => 32, 'no_of_offense' => 1, 'sanction_id' => 21],
            ['id' => 109, 'violation_id' => 32, 'no_of_offense' => 2, 'sanction_id' => 22],
            ['id' => 110, 'violation_id' => 32, 'no_of_offense' => 3, 'sanction_id' => 9],
            ['id' => 111, 'violation_id' => 33, 'no_of_offense' => 1, 'sanction_id' => 21],
            ['id' => 112, 'violation_id' => 33, 'no_of_offense' => 2, 'sanction_id' => 22],
            ['id' => 113, 'violation_id' => 33, 'no_of_offense' => 3, 'sanction_id' => 9],
            ['id' => 114, 'violation_id' => 34, 'no_of_offense' => 1, 'sanction_id' => 23],
            ['id' => 115, 'violation_id' => 35, 'no_of_offense' => 1, 'sanction_id' => 24],
            ['id' => 116, 'violation_id' => 36, 'no_of_offense' => 1, 'sanction_id' => 20],
            ['id' => 117, 'violation_id' => 37, 'no_of_offense' => 1, 'sanction_id' => 8],
            ['id' => 118, 'violation_id' => 37, 'no_of_offense' => 2, 'sanction_id' => 9],
            ['id' => 119, 'violation_id' => 37, 'no_of_offense' => 3, 'sanction_id' => 25],
        ]);
    }
}
